# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0004_auto_20160909_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(-1, 'No'), (0, 'Unsure'), (1, 'Yes')], default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='link',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='rating',
            new_name='score',
        ),
        migrations.AddField(
            model_name='link',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='link',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.AddField(
            model_name='rating',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Link'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
