# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_auto_20160913_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='link',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='object_id',
        ),
    ]
